stages:
  preprocess:
    cmd: python src\data\preprocess.py --config=params.yaml
    params:
      - data_preprocess
      - base
    outs:
      - data/preprocessed/preprocessed_data.csv
  process:
    cmd: python src\data\process.py --config=params.yaml
    params:
      - data_process
      - base
    deps:
      - src\data\preprocess.py
      - data/preprocessed/preprocessed_data.csv
    outs:
      - data/processed/processed_data.csv
  split:
    cmd: python src\data\split.py --config=params.yaml
    params:
      - data_split
      - base
    deps:
      - src\data\process.py
      - data/processed/processed_data.csv
    outs:
      - data/split/train.csv
      - data/split/test.csv
  train:
    cmd: python src\model\train.py --config=params.yaml
    params:
      - model
      - base
    deps:
      - src\data\split.py
      - data/split/train.csv
    outs:
      - models/best_model.pkl
  evaluate:
    cmd: python src\evaluate\evaluate_model.py --config=params.yaml
    params:
      - evaluate
      - base
    deps:
      - src\model\train.py
      - models/best_model.pkl
      - data/split/test.csv
    outs:
      - reports/figures/prediction_vs_true.png
      - reports/metrics/metrics.json


